# Generated by Django 4.1.4 on 2023-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="featured_image/%Y/%m/%d/"),
            preserve_default=False,
        ),
    ]
