# Generated by Django 4.2.17 on 2025-11-02 14:31

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body_html",
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
