# Generated by Django 4.2.17 on 2025-11-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_body_html_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.CharField(
                blank=True,
                help_text="Static image filename, e.g., 'Qué_Bolá_Python_Episodio_1_Cover.png'",
                max_length=500,
            ),
        ),
    ]
