# Generated by Django 4.2.17 on 2025-11-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload blog post cover image",
                upload_to="blog/covers/",
            ),
        ),
    ]
