# Generated by Django 4.1.4 on 2023-01-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_title_post_name_post_is_active_post_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
