# Generated by Django 4.2.17 on 2025-10-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("message", models.TextField(verbose_name="Message")),
            ],
            options={
                "verbose_name": "Contact Profile",
                "verbose_name_plural": "Contact Profiles",
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="home_contac_timesta_67b6b1_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "certificate_link",
                    models.URLField(default="www.github.com/gerozayas"),
                ),
                ("certificate_image", models.ImageField(upload_to="certificates/")),
            ],
            options={
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-date"],
                        name="home_certif_is_acti_862bde_idx",
                    )
                ],
            },
        ),
    ]
