# Generated by Django 4.1.5 on 2023-01-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_image",
            field=models.ImageField(upload_to="static/images/Certificates/"),
        ),
    ]
