# Generated by Django 4.1.4 on 2023-01-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="certificate_image",
            field=models.FilePathField(
                default="C:\\Users\\Gero Zayas\\Downloads\\CODING\\Django\\django-alpha\\static\\images\\Certificates\\CertificateOfCompletion_Learning C_1.jpg",
                path="C:\\Users\\Gero Zayas\\Downloads\\CODING\\Django\\django-alpha\\static\\images",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="certificate_link",
            field=models.URLField(default="www.github.com/gerozayas"),
        ),
    ]
