# Generated by Django 4.1.4 on 2023-01-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_certificate_certificate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_image",
            field=models.FilePathField(
                default="...",
                path="C:\\Users\\Gero Zayas\\Downloads\\CODING\\Django\\django-alpha\\static\\images\\Certificates",
            ),
        ),
    ]
