# Generated by Django 4.1.4 on 2023-01-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_certificate_certificate_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["-date"],
                "verbose_name": "Certificate",
                "verbose_name_plural": "Certificates",
            },
        ),
    ]
