# Generated by Django 4.1.4 on 2023-01-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_certificate_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_image",
            field=models.FilePathField(
                default="C:\\Users\\Gero Zayas\\Downloads\\CODING\\Django\\django-alpha\\static\\images\\Certificates\\CertificateOfCompletion_Learning C_1.jpg",
                path="C:\\Users\\Gero Zayas\\Downloads\\CODING\\Django\\django-alpha\\static\\images\\Certificates",
            ),
        ),
    ]
