# Generated by Django 4.1.5 on 2023-01-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_certificate_certificate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_image",
            field=models.ImageField(upload_to="static/images/Certificates"),
        ),
    ]
