# Generated by Django 4.2.17 on 2025-10-15 05:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("technology", models.CharField(max_length=40)),
                ("github_link", models.URLField()),
                ("image", models.ImageField(upload_to="projects/")),
                ("ranking", models.IntegerField(db_index=True, default=7)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Portfolio Projects",
                "ordering": ["ranking"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "ranking"],
                        name="portfolio_p_is_acti_5a9f74_idx",
                    ),
                    models.Index(fields=["slug"], name="portfolio_p_slug_e96b08_idx"),
                ],
            },
        ),
    ]
