# Generated by Django 4.1.5 on 2023-01-30 12:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("body", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("technology", models.CharField(max_length=40)),
                ("github_link", models.URLField()),
                ("image", models.ImageField(upload_to="static/images/Projects/")),
                ("ranking", models.IntegerField(default=7)),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolio Profiles",
                "ordering": ["ranking"],
            },
        ),
    ]
