# Generated by Django 4.1.4 on 2023-01-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FilePathField(
                path="C:\\Users\\Gero Zayas\\Downloads\\CODING\\Django\\django-alpha\\static\\images"
            ),
        ),
    ]
