# Generated by Django 4.1.4 on 2023-01-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="technology",
            field=models.CharField(max_length=40),
        ),
    ]
