# Generated by Django 4.1.4 on 2023-01-12 14:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_project_github_link_alter_project_technology"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["title"],
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolio Profiles",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
