# Generated by Django 4.2.17 on 2025-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_project_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(
                help_text="Path to static image, e.g., 'static/images/Projects/project.png'",
                max_length=500,
            ),
        ),
    ]
