# Generated by Django 4.1.4 on 2023-01-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0004_alter_project_options_project_body_project_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="ranking",
            field=models.IntegerField(default=7),
        ),
    ]
