# Generated by Django 4.1.4 on 2023-01-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_project_ranking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["ranking"],
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolio Profiles",
            },
        ),
    ]
