# Generated by Django 4.1.5 on 2023-01-28 23:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_alter_project_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="project",
            name="certificate_image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="static/images/Projects"
            ),
            preserve_default=False,
        ),
    ]
