# Generated by Django 4.1.5 on 2023-01-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_remove_project_image_project_certificate_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
